name: iot-frontend
services:
  node:
    build: node
    ports:
     - "8080:8080"
    volumes:
      - ./../:/usr/app
    networks:
      - iot-network
    command: npm run dev

networks:
  iot-network:
    driver: bridge